#!/bin/sh -e

# Add install directory to default search paths.
export CFLAGS="$CFLAGS -L$1/usr/lib -I$1/usr/include"

export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$1/usr/lib/pkgconfig"
PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$1/usr/share/pkgconfig"

sed -i 's/pthread-stubs //' \
    libxcb/configure

sed -i "/^XCBPROTO_XCBINCLUDEDIR/s|=.*|= $1/usr/share/xcb|" \
    libxcb/Makefile.in \
    libxcb/src/Makefile.in

PYMAJOR_MINOR="$(python -c 'import sys; print(sys.version_info.major, ".", sys.version_info.minor, sep="")')"

sed -i "/^XCBPROTO_XCBPYTHONDIR/s|=.*|= $1/usr/lib/python$PYMAJOR_MINOR/site-packages|" \
    libxcb/Makefile.in \
    libxcb/src/Makefile.in

while read -r _ pkg; do
    [ -d "$pkg" ] && (
        cd "$pkg"

        ./configure \
            --prefix=/usr \
            --with-keysymdefdir="$1/usr/include/X11" \
            --disable-static \
            --disable-nls

        make
        make DESTDIR="$1" install

        # Delete libtool files or it'll get mad.
        find "$1" -name \*.la -exec rm -f {} +
    )
done < sources

rm -rf "$1/usr/share" "$1/usr/include" "$1/usr/lib/python"* "$1/usr/lib/pkgconfig"
