#!/bin/sh -e

export DESTDIR="$1"

meson \
	--prefix=/ \
	-Ddefault_library=static \
	inih inih/output

ninja -C inih/output
DESTDIR="$PWD/junk" ninja -C inih/output install

export CFLAGS="$CFLAGS -I$PWD/junk/include"
export LDFLAGS="$LDFLAGS -L$PWD/junk/lib"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$PWD/junk/lib/pkgconfig"

meson \
	--prefix=/usr \
	--libexecdir=/usr/lib \
	. output

ninja -C output
ninja -C output install
