#!/bin/sh -e

for p in *.patch; do
    patch -p1 < "$p"
done

PATH_MAX="$(getconf PATH_MAX /)"
export CPPFLAGS="$CPPFLAGS -DPATH_MAX=$PATH_MAX"

export DESTDIR="$1"

kiss list libsndfile && sndfile=enabled

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Ddbus=disabled \
    -Dtests=disabled \
    -Dpw-cat="${sndfile:-disabled}" \
    . output

ninja -C output
ninja -C output install

:>"$1/usr/share/pipewire/media-session.d/with-alsa"
