#!/bin/sh -e

patch -p1 < x264-no-bash.patch

sed 's/$CC $CFLAGS conftest.c/& -ffat-lto-objects/' -i configure

./configure \
    --prefix=/usr \
    --disable-swscale \
    --enable-pic \
    --enable-shared

make
make DESTDIR="$1" install
