#!/bin/sh -e

patch -p1 < syntax-highlighting.patch

make
make DESTDIR="$1" PREFIX="/usr" MANPREFIX="/usr/share/man" install

install -Dm644 stagit.conf  "$1/etc/stagit/stagit.conf"
install -Dm755 post-receive "$1/etc/stagit/post-receive"

for script in stagit-gen-index stagit-new-repo; do
    install -Dm755 "$script" "$1/usr/bin/$script"
done
