#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dvapi=false \
    -Dintrospection=disabled \
    -Dexamples=false \
    -Dtests=false \
    . output

ninja -C output
ninja -C output install
