#!/bin/sh

make \
    DESTDIR="$1" \
    PREFIX=/usr \
    all-dynamic \
    install-dynamic \
    install-manpages

# ncurses-compatible script
install -Dm755 ncurses5-config "$1/usr/bin/ncurses5-config"
