#!/bin/sh -e

mkdir -p "$1/etc/profile.d" "$1/opt"

unzip "./gradle-$2-bin.zip"
cp -R "./gradle-$2" "$1/opt/gradle-$2"

echo "export PATH=\$PATH:/opt/gradle-$2/bin" > "$1/etc/profile.d/gradle.sh"
chmod +x "$1/etc/profile.d/gradle.sh"
