#!/bin/sh -e

mkdir -p "$1/etc/profile.d" "$1/opt"

cat > "$1/etc/profile.d/flutter.sh" <<EOF
export FLUTTER_HOME=/opt/flutter
export DART_VM_OPTIONS=--root-certs-file=/etc/ssl/cert.pem
export PATH=\$PATH:\$FLUTTER_HOME/bin
EOF

cp -R "$PWD" "$1/opt/flutter"

cd "$1/opt/flutter"

# These files must be RW by all users
chmod a+rw \
    version \
    bin/cache/lockfile \
    bin/cache/usbmuxd.stamp \
    bin/cache/libimobiledevice.stamp
