#!/bin/sh -euf

. /etc/stagit/stagit.conf

src="$(pwd)"
name=$(basename "$src")
dst="$WWW_HOME/$(basename "$name" '.git')"
mkdir -p "$dst"
cd "$dst" || exit 1

echo "[stagit] building $dst"
/usr/bin/stagit "$src"

echo "[stagit] linking $dst"
ln -sf log.html index.html

for file in style.css logo.png favicon.ico; do
    ln -sf "../$file" "$file"
done
