#!/bin/sh -e

NAME="Qogir-dark"
THEME_DIR="$1/usr/share/themes/$NAME"

mkdir -p "$THEME_DIR/gtk-3.0"

cp -R src/gtk/assets/assets "$THEME_DIR/gtk-3.0/assets"
cp -R src/gtk/assets/assets-common/* "$THEME_DIR/gtk-3.0/assets/"

cp src/gtk/theme-3.0/gtk-Dark.css "$THEME_DIR/gtk-3.0/gtk.css"

cat > "$THEME_DIR/index.theme" <<EOF
[Desktop Entry]
Type=X-GNOME-Metatheme
Name=$NAME
Comment=An Clean Gtk+ theme based on Flat Design
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=$NAME
MetacityTheme=$NAME
IconTheme=$NAME
CursorTheme=$NAME
ButtonLayout=menu:minimize,maximize,close
EOF
