#!/bin/sh -e

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --enable-libuuid \
    --enable-libblkid \
    --enable-libmount \
    --disable-all-programs

make
make DESTDIR="$1" install
