#!/bin/sh -e

version="$2"

sh "NVIDIA-Linux-x86_64-$version-no-compat32.run" --extract-only
cd "NVIDIA-Linux-x86_64-$version-no-compat32"

install -Dm755 "libEGL_nvidia.so.$version"     "$1/usr/lib/libEGL_nvidia.so.$version"
install -Dm755 "libnvidia-eglcore.so.$version" "$1/usr/lib/libnvidia-eglcore.so.$version"
install -Dm755 "libnvidia-glsi.so.$version"    "$1/usr/lib/libnvidia-glsi.so.$version"
install -Dm755 "libnvidia-ml.so.$version"      "$1/usr/lib/libnvidia-ml.so.$version"

install -Dm644 "10_nvidia.json"     "$1/usr/share/glvnd/egl_vendor.d/10_nvidia.json"
install -Dm644 "nvidia_icd.json"    "$1/usr/share/vulkan/icd.d/nvidia_icd.json"
install -Dm644 "nvidia_layers.json" "$1/usr/share/vulkan/implicit_layer.d/nvidia_layers.json"

install -Dm755 nvidia-smi      "$1/usr/bin/nvidia-smi"
install -Dm644 nvidia-smi.1.gz "$1/usr/share/man/man1/nvidia-smi.1.gz"

# soname links
for lib in "$1/usr/lib/"*.so*; do
    soname=$(dirname "$lib")/$(readelf -d "$lib" | awk '/SONAME/ { print $5 }' | tr -d '[]')
    base=$(echo "$soname" | sed -r 's/(.*).so.*/\1.so/')
    [ -e "$soname" ] || ln -s "$(basename "$lib")" "$soname"
    [ -e "$base" ] || ln -s "$(basename "$soname")" "$base"
done

# kernel modules
cd kernel
make modules
install -Dm644 ./*.ko -t "$1/usr/lib/modules/${KERNEL_UNAME:-$(uname -r)}/extra"
