#!/bin/sh -e

NAME="Qogir-dark"
THEMEDIR="$1/usr/share/icons/$NAME"

mkdir -p "$THEMEDIR"

(
    cd "$1/usr/share/icons"
    ln -s "$NAME" default
)

(
    cd src

    sed "s|Qogir|$NAME|g" index.theme > _
    mv -f _ index.theme

    cp -R \
        index.theme \
        cursors/dist-dark/cursors \
        "$THEMEDIR"
)
