#!/bin/sh -e

for p in *.patch; do
    patch -p1 < "$p"
done

export LDFLAGS="$LDFLAGS --static"
export PKG_CONFIG="pkg-config --static"

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --disable-shared \
    --enable-clang-wrappers \
    --enable-clang-rewrite-includes \
    --without-man

make
make DESTDIR="$1" install
