#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DHUNTER_ENABLED=ON \
    -DUSE_BUNDLED_BOOST=OFF \
    -DUSE_BUNDLED_OLM=OFF \
    -DUSE_BUNDLED_OPENSSL=OFF

cmake --build   build
cmake --install build
