#!/bin/sh -e

mkdir -p "$1/usr/bin"

for bin in diff patch; do
    # shellcheck disable=2086
    ${CC:-cc} $CFLAGS -DBSDIFF_EXECUTABLE -DBSPATCH_EXECUTABLE -lbz2 $LDFLAGS \
        "bs${bin}.c" -o "$1/usr/bin/bs$bin"
done
