#!/bin/sh -e

export DESTDIR="$1"

sed '/add_subdirectory(cli)/d' CMakeLists.txt > _
mv -f _ CMakeLists.txt

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_QT_UI=OFF

cmake --build   build
cmake --install build
