#!/bin/sh -e

export DESTDIR="$1"

sed -i "s|subdir('doc')||" meson.build

meson \
    --prefix=/usr \
    -Dterminfo=disabled \
    -Db_lto=true \
    . output

ninja -C output
ninja -C output install
