#!/bin/sh -e

autoreconf -i

./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --sbindir=/usr/bin

make \
    PROGRAMS='dbclient dropbear dropbearconvert dropbearkey scp' \
    SCPPROGRESS=1

make DESTDIR="$1" install
make DESTDIR="$1" PROGRAMS=scp install

install -Dm755 run "$1/etc/sv/dropbear/run"

ln -sf /run/runit/supervise.dropbear "$1/etc/sv/dropbear/supervise"
