#!/bin/sh -e

export LDFLAGS="$LDFLAGS -lucontext"
export CFLAGS="$CFLAGS -fno-stack-protector"

./configure \
    --prefix=/usr \
    --enable-cxx-exceptions \
    --disable-tests

make
make DESTDIR="$1" install
