#!/bin/sh -e

export DESTDIR="$1"

sed -i "s|fcft/||g" meson.build ./*.c ./*.h
sed -i "s|subdir('doc')||" meson.build

meson \
    --prefix=/usr \
    . output

ninja -C output
ninja -C output install
