#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

(
    cp .config .cfgbak

    make olddefconfig
    make prepare

    cd zfs

    ./configure \
        --with-linux="$PWD/.." \
        --enable-linux-builtin

    ./copy-builtin "$PWD/.."

    mv -f .cfgbak .config
)

make olddefconfig

make syncconfig
KERNELRELEASE="$(make kernelrelease)"

modulesdir="$1/usr/lib/modules/$KERNELRELEASE"
builddir="$modulesdir/build"

make
make INSTALL_MOD_PATH="$1/usr" INSTALL_MOD_STRIP=1 modules_install

rm -f "$modulesdir/build" "$modulesdir/source"

for dir in kernel arch/x86/kernel drivers/md net/mac80211 tools/objtool; do
    mkdir -p "$builddir/$dir"
done

cp .config Makefile Module.symvers System.map "$builddir"
cp kernel/Makefile "$builddir/kernel/"
cp arch/x86/Makefile "$builddir/arch/x86/"
cp arch/x86/kernel/asm-offsets.s "$builddir/arch/x86/kernel/"
cp drivers/md/*.h "$builddir/drivers/md/"
cp net/mac80211/*.h "$builddir/net/mac80211/"
cp tools/objtool/objtool "$builddir/tools/objtool/"

cp -R scripts "$builddir/scripts"
cp -R include "$builddir/include"
cp -R arch/x86/include "$builddir/arch/x86/include"

find . -name "Kconfig*" -exec install -Dm644 {} "$builddir/{}" \;

rm -rf "$builddir/Documentation"
find -L "$builddir" -type l -exec rm -rf {} +
find "$builddir" -type f -name "*.o" -exec rm -rf {} +

mkdir -p "$1/boot/EFI"
cp arch/x86/boot/bzImage "$1/boot/EFI/KISS.efi"
