#!/bin/sh -e

IFS=" "

grep '^Link: nvidia/' WHENCE | while read -r _ file _ src; do
    mkdir -p "$(dirname "$file")"
    ln -sfv "$src" "$file"
done

mkdir -p "$1/usr/lib/firmware"
cp -R amd-ucode amdgpu mediatek nvidia rtlwifi "$1/usr/lib/firmware/"
