#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    . output

ninja -C output
ninja -C output install

install -Dm644 10_nvidia_wayland.json \
    "$1/usr/share/egl/egl_external_platform.d/10_nvidia_wayland.json"
