#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

sed 's/FORCE//' arch/x86/crypto/Makefile > _
mv -f _ arch/x86/crypto/Makefile

make olddefconfig

grep 'CONFIG_MODULES=y' .config && {
    printf '%s\n' 'Module support must be disabled' >&2
    exit 1
}

make

mkdir -p "$1/boot"
cp arch/x86/boot/bzImage "$1/boot/vmlinuz-$2"
