#!/bin/sh -e

# Uncomment if using valgrind or similar.
# :>nostrip

./configure \
    --prefix=/usr/musl \
    --syslibdir=/usr/musl/lib \
    --enable-wrapper=gcc
# Uncomment if using valgrind or similar.
#   --enable-debug

make
make DESTDIR="$1" install

mkdir -p "$1/usr/bin" "$1/usr/lib"
ln -s  /usr/musl/lib/ld-musl-x86_64.so.1 "$1/usr/musl/bin/ldd"

# Fix incorrect symlink to libc.so.
ln -sf libc.so "$1/usr/musl/lib/ld-musl-x86_64.so.1"

# Install BSD compatibility headers.
install -Dm 755 cdefs.h "$1/usr/musl/include/sys/cdefs.h"
install -Dm 755 queue.h "$1/usr/musl/include/sys/queue.h"
install -Dm 755 tree.h  "$1/usr/musl/include/sys/tree.h"

ln -s ../musl/bin/musl-gcc "$1/usr/bin/musl-gcc"
