#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-double-bracket \
    --disable-dirstack \
    --disable-socket \
    --disable-array \
    --enable-lineedit \
    --with-term-lib="curses terminfo"

make
make DESTDIR="$1" install

ln -s yash "$1/usr/bin/sh"
