#!/bin/sh -e

# Fix build with GCC 10.
export CFLAGS="$CFLAGS -fcommon"

sed -i 's/-l.curses/& -lterminfo/' configure

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --enable-cgroup \
    --disable-unicode \
    --enable-taskstats

make
make DESTDIR="$1" install
